---
title: "Cho Lab Technical Exam"
date: 2023-01-10
output: html_document
---

### Instructions
- This is an open-book assessment that may take few hours to complete.
- All tools, languages, and resources are fair game.
- **Upload all files for your submission [here](https://forms.gle/PM3RMSsj5V4FiZ6bA)** with titles that include your name (e.g. `chris-tastad-output.pdf`)

### Questions
1. **Project Proposal - Consider an unanswered research question of interest to you:**
    - Construct a *high level* outline of a project to address this question detailing specific aim(s), method(s), statistical design, and predicted results to the extent you are able.
    - Feel free to use the template given [here](https://www.dropbox.com/scl/fo/uvvrqirtkykgc5ekyplk8/h?dl=0&rlkey=2qqruj54ie6khikpxxx5rsyz2) or write in a typical proposal format.
    - *Note of emphasis:* This is not an endurance exercise, and being excessively verbose is not required. Instead, we are hoping to get a sense of what is interesting to you and how you would execute your approach. Realistically shoot for less than a few hundred words.
1. **Consider the unknown sequencing data given [here](https://www.dropbox.com/sh/11geyzga66zah4p/AADZEDlsW_pjLy9bliHIdEPIa?dl=0).**
    - Perform a QC process on this data, and aggregate your results into a single output.
      - a suggested approach would be to use a tool combo like fastQC/MultiQC
    - Provide a detailed assessment of the nature and quality of this data given your QC output.
    - Speculate on the type of sequencing used to generate this data.

